config/routes.rb
Rails.application.routes.draw do

  get 'prescriptions/new'

  authenticated :user do
    root :to => 'passthrough#minirouter' # Look up the PassthroughController
  end

  devise_scope :user do
    root to: "users/registrations#new"
  end

  get 'drivers/new',                to: 'driver_registrations#new'
  get 'drivers/switch',             to: 'drivers#switch'
  post 'drivers',                   to: 'driver_registrations#create'
  post 'drivers/verify',            to: 'drivers#verify'

  get 'prescriptions/new',          to: 'prescriptions#new'
  post 'prescriptions/create',       to: 'prescriptions#create'


  get 'orders/claim',               to: 'orders#claim'
  post 'order/add_to_cart',         to: 'orders#add_to_cart'



  devise_for :users, controllers: { registrations: "users/registrations" }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # resources :order_products, only: [ :index, :show, :new, :create ] do
    #   resources :products, only: :create
    # end

  resources :customers, only: [ :show]
  resources :drivers, only: [ :show ]
  resources :verification_codes
    resources :products, only: [ :index, :show, :new, :create ] do
      resources :order_products, only: [ :index, :show, :new, :create ]
    end
    resources :orders, only: [ :index, :show, :new, :create ] do
      resources :payments, only: [ :create]
      resources :order_products, only: [ :index, :show, :new, :create ] do
        resources :products, only: [ :index, :show, :new, :create ]
      end
    end
    resources :customers, only: [ :show] do
      resources :customer_addresses, only: [ :create]
    end

    resources :drivers, only: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :customer_addresses
  has_many :orders
  def full_name
    "#{user.firt_name} #{user.last_name}"
  end
end

app/models/customer_address.rb
class CustomerAddress < ApplicationRecord
  belongs_to :customer
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :user
  has_many :orders

  include AASM

  aasm :column => :status do
    state :inactive, :initial => true
    state :active

    event :activate do
      transitions :from => :inactive, :to => :active
    end

    event :deactivate do
      transitions :from => :active, :to => :inactive
    end

  end

  aasm :column => :verification_status do
    state :unverified, :initial => true
    state :verified

    event :verify do
      transitions :from => :unverified, :to => :verified
    end

  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :driver, optional: true
  has_many :order_products, inverse_of: :order
  has_many :products, through: :order_products

  monetize :amount_cents

  accepts_nested_attributes_for :order_products

  include AASM

  aasm do
    state :unpaid, initial: true
    state :unclaimed
    state :claimed
    state :shopping
    state :processed
    state :delivered

    event :unpaid do
      transitions from: [ :claimed, :shopping, :processed, :delivered, :unclaimed ], to: :unpaid
    end

    event :unclaim do
      transitions from: :unpaid, to: :unclaimed
    end

    event :claim do
      transitions from: :unclaimed, to: :claimed
    end

    event :shop do
      transitions from: :claimed, to: :shopping
    end

    event :process do
      transitions from: :shopping, to: :processed
    end

    event :deliver do
      transitions from: :processed, to: :delivered
    end

  end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order, inverse_of: :order_products
  belongs_to :product

  accepts_nested_attributes_for :product
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :customer

  validates :interval, inclusion: { in: [ "weekly", "monthly", "bimonthly", "yearly" ] }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products
  has_many :orders, through: :order_products
  has_attachment :photo
  monetize :price_cents

  def to_s
    name
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    @product.photo_url = product_params[:photo_url]
    @product.save!
  end

  private

  def product_params
    params.require(:product).permit(:name, :photo)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :customer
  has_one :driver
end

app/models/verification_code.rb
class VerificationCode < ApplicationRecord
  belongs_to :user
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def show
    @customer = current_user.customer
    @orders = @customer.orders
    authorize @customer
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
    @orders             = Order.all
    authorize @orders
  end

  def add_to_cart
    order               = Order.find(params[:id])
    order_products      = JSON.parse(params[:json])

    order_products.each do |id, quantity|
      order.order_products.create(product: Product.find(id), quantity: quantity)
    end
    authorize order
    redirect_to order_path(order)
  end

  def show
    @order              = Order.find(params[:id])
    @customer           = Customer.find(current_user.customer)
    @customer_address   = CustomerAddress.new
    @customer_addresses = CustomerAddress.where(customer_id: current_user)
    @order.amount       = calculate_amount(@order)
    @order.save!
    authorize @order
  end

  def new
    @order              = current_user.customer.orders.create
    @products           = Product.all
    @prescription       = Prescription.new
    authorize @products
    # authorize @prescription
  end

  def create
    @order = current_user.customer.orders.create(order_params)
    redirect_to order_path(@order)
    authorize @order
  end

  def calculate_amount(order)
    sum = 0
    order.order_products.each do |order_product|
      subsum = order_product.quantity * order_product.product.price
      sum += subsum
    end
    return sum
  end

  def claim
    @order              = Order.find(params[:id])
    @order.claim!
    @order.driver       = current_user.driver
    @order.save!
    authorize @order
  end

  private

  def order_params
    params.require(:order).permit(:id, order_products_attributes: [ :quantity, :product_id, products_attributes: [:name] ])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    authorize @pages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/passthrough_helper.rb
module PassthroughHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/verifications_helper.rb
module VerificationsHelper
end

app/views/customers/_customer_address_show.html.erb
<% if customer.customer_addresses.empty? %>
<div style="margin: 40px;"><button type="button" class="btn btn-secondary" style="background-color: #e6e6e6
; display: block; float: none; width: 100%; max-width: 100%;">+ New Delivery Address</button></div>
<% else %>

<h3 style="color: grey;"> Your addresses </h3>
<hr/>
<% customer.customer_addresses.each do|address| %>
  <h4 style="color: grey;"> <%= address.address %></h4>
  <!-- add deletion and update -->
<% end %>
<% end %>

app/views/customers/_customer_history_show.html.erb
<h1 style="color: grey;>Order history</h1>
<br/>
<% if @orders.where(aasm_state: 'delivered').empty? %>
<h3 style="color: grey;>You have no delivered orders yet. Get started and create your order <%= link_to "here", new_order_path %></h3>
<% else %>
<h1 style="color: grey;">Delivered orders</h1>
<% @orders.where(aasm_state: 'delivered').each do |order| %>

<div  style="color: grey;">
  <h4> Order-id: <%= order.id  %> </h4>
  <h4> Order -  status: <%= order.aasm_state %> </h4>
  <h4> delivery date: <%= order.delivery_date %> </h4>
  <h4> Your driver was <%= order.driver.user.first_name %></h4>
  <h4> <%= link_to "See Order", order_path(order) %></h4>
</div>

<% end %>

<% end %>

app/views/customers/_customer_orders_show.html.erb
<% if orders.count === 0 %>
<div class="fadeinwords">
Welcome, <%= current_user.first_name.capitalize%>! |It looks like you haven't created an order yet. |To create your first order click |<%= link_to "HERE", new_order_path %>
</div>

<% else %>
<h2 style="text-align:left; color: grey;;">
Your Orders
<span style="float:right;"><%= link_to "New Order", new_order_path %></span>
</h2>
<hr/>
<% end %>

<% counter = 0 %>
<% orders.each do |order| %>
  <% if order.unclaimed? || order.claimed? || order.shopping? %>
  <% counter += 1 %>

  <div>
    <h4 style="color: grey;"> Order-id: <%= order.id  %> </h4>
    <h4 style="color: grey;"> Status of your order: <%= order.aasm_state %> </h4>
  </div>
  <% end %>
<% end %>

app/views/customers/_customer_profile_show.html.erb
<div class="context-container">
  <div style="color: grey;">
    <h3>Account Information</h3>
    <div class="row">
      <div class="col-xs-4"><h4> Email </h4></div>
      <div class="col-xs-4"><h4> <%= customer.user.email %></h4></div>
      <div class="col-xs-4"><h4><%= link_to "Update", edit_user_registration_path %></h4></div>
    </div>
    <div class="row">
      <div class="col-xs-4"><h4> Password </h4></div>
      <div class="col-xs-4"><h4> ●●●●●●</h4></div>
      <div class="col-xs-4"><h4><%= link_to "Change", edit_user_registration_path %></h4></div>
    </div>
  </div>
  </div>
<div style="padding-top: 2px; background-color: grey;"></div>
<div class="context-container" style="color: grey;">
  <h3>Personal Infomation</h3>
  <div class="row">
    <div class="col-xs-4"><h4> First Name </h4></div>
    <div class="col-xs-4"><h4> <%= customer.user.first_name %></h4></div>
    <div class="col-xs-4"><h4><%= link_to "Change", edit_user_registration_path %></h4></div>
  </div>
  <div class="row">
    <div class="col-xs-4"><h4> Last Name </h4></div>
    <div class="col-xs-4"><h4> <%= customer.user.last_name %> </h4></div>
    <div class="col-xs-4"><h4><%= link_to "Change", edit_user_registration_path %></h4></div>
  </div>
  <div class="row">
    <div class="col-xs-4"><h4> Phone Number </h4></div>
    <div class="col-xs-4"><h4> <%= current_user.customer.phone_number %> </h4></div>
    <div class="col-xs-4"><% if current_user.customer.phone_number.nil? %>
      <h4>Add</h4>


        <% else %>
        <h4>Update</h4>
        <% end %>


      </div>
    </div>
    <div class="row">
      <div class="col-xs-4"><h4> Customer ID </h4></div>
      <div class="col-xs-4"><h4> <%= customer.id %></h4></div>
      <div class="col-xs-4"><h4> </h4></div>
    </div>
  </div>

app/views/customers/show.html.erb
<div class="dashboard-wrapper">
  <div class="row">
    <div class="col-xs-3">
      <div class="tabs-container">
        <div class="tab active" data-target="#orders"> <!-- lav underDivs se instacart -->
          <div class ="col-xs-1"><i class="fa fa-shopping-cart" aria-hidden="true"></i></div>
          <div class ="col-xs-7 col-xs-offset-1 dashboard-text"><h4>Orders</h4></div>
          <div class ="col-xs-3 text-right"><i class="fa fa-angle-double-right" aria-hidden="true"></i></div>
        </div>
        <div class="tab" data-target="#profile">
          <div class ="col-xs-1"><i class="fa fa-user" aria-hidden="true"></i></div>
          <div class ="col-xs-7 col-xs-offset-1 dashboard-text"><h4>Profile</h4></div>
          <div class ="col-xs-3 text-right"><i class="fa fa-angle-double-right" aria-hidden="true"></i></div>
        </div>
        <div class="tab" data-target="#History">
          <div class ="col-xs-1"><i class="fa fa-list" aria-hidden="true"></i></div>
          <div class ="col-xs-7 col-xs-offset-1 dashboard-text"><h4>Order History</h4></div>
          <div class ="col-xs-3 text-right"><i class="fa fa-angle-double-right" aria-hidden="true"></i></div>
        </div>
        <div class="tab" data-target="#Addresses">
          <div class ="col-xs-1"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
          <div class ="col-xs-7 col-xs-offset-1 dashboard-text"><h4>Delivery Addresses</h4></div>
          <div class ="col-xs-3 text-right"><i class="fa fa-angle-double-right" aria-hidden="true"></i></div>
        </div>
      </div>
    </div>
    <div class="context-container col-xs-7">
      <div class="tab-content" id="orders">
        <%= render 'customer_orders_show.html.erb', orders: @orders, customer: @customer %>
      </div>
      <div class="tab-content hidden" id="profile">
        <%= render 'customer_profile_show.html.erb', customer: @customer %>
      </div>
      <div class="tab-content hidden" id="History">
        <%= render 'customer_history_show.html.erb', customer: @customer %>
      </div>
      <div class="tab-content hidden" id="Addresses">
        <%= render 'customer_address_show.html.erb', customer: @customer %>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>

<script>
  $(document).ready(function () {
    $(function(){

      $(".tab").on("click", function(e){
        // Change active tab
        $('.tab').removeClass('active')
        $(this).addClass('active')

        // Hide all tab-content (use class="hidden")
        $('.tab-content').addClass('hidden')

        // Show target tab-content (use class="hidden")
        var id = $(".active").data("target")
        $(id).removeClass('hidden')
      });
    });
  });
</script>
<% end %>