config/routes.rb
Rails.application.routes.draw do

  get 'prescriptions/new'

  authenticated :user do
    root :to => 'passthrough#minirouter' # Look up the PassthroughController
  end

  devise_scope :user do
    root to: "users/registrations#new"
  end

  get 'drivers/new',                to: 'driver_registrations#new'
  get 'drivers/switch',             to: 'drivers#switch'
  post 'drivers',                   to: 'driver_registrations#create'
  post 'drivers/verify',            to: 'drivers#verify'

  get 'prescriptions/new',          to: 'prescriptions#new'
  post 'prescriptions/create',       to: 'prescriptions#create'


  get 'orders/claim',               to: 'orders#claim'
  post 'order/add_to_cart',         to: 'orders#add_to_cart'



  devise_for :users, controllers: { registrations: "users/registrations" }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # resources :order_products, only: [ :index, :show, :new, :create ] do
    #   resources :products, only: :create
    # end

  resources :customers, only: [ :show]
  resources :drivers, only: [ :show ]
  resources :verification_codes
    resources :products, only: [ :index, :show, :new, :create ] do
      resources :order_products, only: [ :index, :show, :new, :create ]
    end
    resources :orders, only: [ :index, :show, :new, :create ] do
      resources :payments, only: [ :create]
      resources :order_products, only: [ :index, :show, :new, :create ] do
        resources :products, only: [ :index, :show, :new, :create ]
      end
    end
    resources :customers, only: [ :show] do
      resources :customer_addresses, only: [ :create]
    end

    resources :drivers, only: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :customer_addresses
  has_many :orders
  def full_name
    "#{user.firt_name} #{user.last_name}"
  end
end

app/models/customer_address.rb
class CustomerAddress < ApplicationRecord
  belongs_to :customer
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :user
  has_many :orders

  include AASM

  aasm :column => :status do
    state :inactive, :initial => true
    state :active

    event :activate do
      transitions :from => :inactive, :to => :active
    end

    event :deactivate do
      transitions :from => :active, :to => :inactive
    end

  end

  aasm :column => :verification_status do
    state :unverified, :initial => true
    state :verified

    event :verify do
      transitions :from => :unverified, :to => :verified
    end

  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :driver, optional: true
  has_many :order_products, inverse_of: :order
  has_many :products, through: :order_products

  monetize :amount_cents

  accepts_nested_attributes_for :order_products

  include AASM

  aasm do
    state :unpaid, initial: true
    state :unclaimed
    state :claimed
    state :shopping
    state :processed
    state :delivered

    event :unpaid do
      transitions from: [ :claimed, :shopping, :processed, :delivered, :unclaimed ], to: :unpaid
    end

    event :unclaim do
      transitions from: :unpaid, to: :unclaimed
    end

    event :claim do
      transitions from: :unclaimed, to: :claimed
    end

    event :shop do
      transitions from: :claimed, to: :shopping
    end

    event :process do
      transitions from: :shopping, to: :processed
    end

    event :deliver do
      transitions from: :processed, to: :delivered
    end

  end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order, inverse_of: :order_products
  belongs_to :product

  accepts_nested_attributes_for :product
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :customer

  validates :interval, inclusion: { in: [ "weekly", "monthly", "bimonthly", "yearly" ] }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products
  has_many :orders, through: :order_products
  has_attachment :photo
  monetize :price_cents

  def to_s
    name
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    @product.photo_url = product_params[:photo_url]
    @product.save!
  end

  private

  def product_params
    params.require(:product).permit(:name, :photo)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :customer
  has_one :driver
end

app/models/verification_code.rb
class VerificationCode < ApplicationRecord
  belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
    @orders             = Order.all
    authorize @orders
  end

  def add_to_cart
    order               = Order.find(params[:id])
    order_products      = JSON.parse(params[:json])

    order_products.each do |id, quantity|
      order.order_products.create(product: Product.find(id), quantity: quantity)
    end
    authorize order
    redirect_to order_path(order)
  end

  def show
    @order              = Order.find(params[:id])
    @customer           = Customer.find(current_user.customer)
    @customer_address   = CustomerAddress.new
    @customer_addresses = CustomerAddress.where(customer_id: current_user)
    @order.amount       = calculate_amount(@order)
    @order.save!
    authorize @order
  end

  def new
    @order              = current_user.customer.orders.create
    @products           = Product.all
    @prescription       = Prescription.new
    authorize @products
    # authorize @prescription
  end

  def create
    @order = current_user.customer.orders.create(order_params)
    redirect_to order_path(@order)
    authorize @order
  end

  def calculate_amount(order)
    sum = 0
    order.order_products.each do |order_product|
      subsum = order_product.quantity * order_product.product.price
      sum += subsum
    end
    return sum
  end

  def claim
    @order              = Order.find(params[:id])
    @order.claim!
    @order.driver       = current_user.driver
    @order.save!
    authorize @order
  end

  private

  def order_params
    params.require(:order).permit(:id, order_products_attributes: [ :quantity, :product_id, products_attributes: [:name] ])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    authorize @pages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/order_products_helper.rb
module OrderProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/passthrough_helper.rb
module PassthroughHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/verifications_helper.rb
module VerificationsHelper
end

app/views/orders/_all_medicines.html.erb
 <h3 style="margin-left: 15px; color:grey;">All Products</h3>
 <div class="shopping-page-wrapper">
  <div style="padding: 20px; margin-bottom: 0px !important;">
    <div class="row">
      <% @products.each do |product| %>

      <div style=":focus {outline:0;}" onmouseenter="showQuantityControl('<%= product.id %>')" onmouseleave="hideQuantityControl('<%= product.id %>')">
        <div class="col-xs-3">
          <div class="card product-info" style="width: 150px; height: 100px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= product.url %>');">
            <div class="card-category" id='<%= product.id %>'> </div>
            <div data-product-id="<%= product.id %>" data-quantity=0 class="quantity-control" id='quantity-<%= product.id %>'>
              <span onclick="subtractOne('<%= product.id %>')" class="square subtract"> - </span>
              <span onclick="addOne('<%= product.id %>')" class="square add" style=""> +ADD </span>
            </div>
            <!-- <img class="card-user avatar" src=""> -->
          </div>
          <div class="product-card">
            <h5><%= product.name %></h5>
            <h6> product description / price</h6>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
<script>

  var orderProducts = {}

  function addOne(id) {
    var newQuantity = $('#quantity-' + id).data('quantity') + 1
    $('#quantity-' + id).data('quantity', newQuantity);
    console.log(  $('#quantity-' + id).data('quantity')  );

  };

  function subtractOne(id) {
    var quantity = $('#quantity-' + id).data('quantity')
    if ( quantity > 0 ) {
      var newQuantity = quantity - 1
      $('#quantity-' + id).data('quantity', newQuantity)
    }
    else {
      $('#quantity-' + id).data('quantity', 0)
    }
    var subtractQuantity = $('#quantity-' + id).data('quantity') - 1
    $('#quantity-' + id).data('quantity', newQuantity)
    console.log(  $('#quantity-' + id).data('quantity')  );

  };

    // define functions below
    function addItem(id) {
      $.ajax({
        type:'GET',
        url:'/orders/claim',
        data: { id: id },
        success:function(){
          console.log("Done");
        }
      });
      $('#' + 'confirm-' + id).hide();
      $('#' + 'container-' + id).slideUp();
    }

    $('.quantity-control').hide();

    function showQuantityControl(id) {
      $('#' + 'quantity-' + id).show();
    }

    function hideQuantityControl(id) {
      $('#' + 'quantity-' + id).hide();
    }

    function hideThis(id) {
      $("#" + id).parent('div').hide();
      $('#' + 'card-' + id).removeClass('fade');
    }

    function showThis(id) {
      $("#" + id).parent('div').fadeIn();
    }

  </script>
  <% end %>

app/views/orders/_basket.html.erb
<div onclick="createOrderProducts('<%= @order.id %>')" id="create-order-'<%= @order.id %>'" style="text-align: center;">
  <%= link_to "Place order", order_path(@order), class: "btn btn-primary" %>
</div>

app/views/orders/_new_prescription.html.erb
<h1 style="margin-left: 30px">Add a new prescription</h1>
<div style="width: 600px; text-align: left; padding: 30px" class="text-center">
  <%= simple_form_for @prescription, url: prescriptions_create_path(@prescription), remote: true do |f| %>
    <%= f.input :number, label: 'Your 16-digit Rx Number', placeholder: 'Prescription # here' %>
    <br>
    <%= f.input :interval, label: 'How often will you need this prescription?', placeholder: 'Weekly, monthly, bimonthly etc.' %>
    <br>
    <%= f.submit "Add prescription", class: "btn btn-success btn-block" %>
  <% end %>
</div>

app/views/orders/_suggested_categories_show.html.erb
<h3 style="margin-left: 15px; color:grey;">Most bought</h3>
<div class="shopping-page-wrapper">
  <div style="padding: 20px;">
    <div class ="your-class" id="order-display">
      <% @products.first(12).each do |product| %>
      <%= render "shared/product_card", product: product %>
      <% end %>
    </div>
  </div>
</div>

<h3 style="margin-left: 15px; color:grey;">Pain relief</h3>
<div class="shopping-page-wrapper">
  <div style="padding: 20px;">

    <div class ="your-class" id="order-display">
      <% @products.last(12).each do |product| %>
      <%= render "shared/product_card", product: product %>
      <% end %>
    </div>

  </div>
</div>

<h3 style="margin-left: 15px; color:grey;">Allergy relief</h3>
<div class="shopping-page-wrapper">
  <div style="padding: 20px;">

    <div class ="your-class" id="order-display">
      <% @products.each do |product| %>
      <% unless product.id == 1 || product.id == 2 ||product.id == 3 ||product.id == 4 %>
        <%= render "shared/product_card", product: product %>
        <% end %>
      <% end %>
    </div>
    <br>
    <br>
  </div>
</div>

app/views/orders/new.html.erb
<div class="card1" style="background-image: linear-gradient(rgba(0,0,0,0.9), rgba(0,0,0,0.2)), url('<%= asset_path "banner.jpg"%>');">
  <div style="text-align: center; padding: 100px; padding-bottom: 75px;">
    <h1 style="font-family: 'Quicksand', sans-serif;">Your medicine, when you need it.</h1>
  </div>

  <div style="opacity: 0.7" class="box searchform">
    <div class="container-3">
      <span class="icon"><i class="fa fa-search"></i></span>
      <input type="search" id="search" placeholder="What can we get for you today?" />
    </div>
  </div>

</div>
<div class="wrapper" style="background-color: #ededed">
  <div class="row">
    <div class="col-xs-3">
      <div class="tabs-container">

        <div class="tab" data-target="#suggestedcats"> <!-- lav underDivs se instacart -->
          <div class ="col-xs-1"><i class="fa fa-shopping-cart" aria-hidden="true"></i></div>
          <div class ="col-xs-7 col-xs-offset-1 dashboard-text"><h4>Suggested Categories</h4></div>
          <div class ="col-xs-3 text-right"><i class="fa fa-angle-double-right" aria-hidden="true"></i></div>
        </div>
        <div class="tab" data-target="#allmedicines">
          <div class ="col-xs-1"><i class="fa fa-medkit" aria-hidden="true"></i></div>
          <div class ="col-xs-7 col-xs-offset-1 dashboard-text"><h4>All medicines</h4></div>
          <div class ="col-xs-3 text-right"><i class="fa fa-angle-double-right" aria-hidden="true"></i></div>
        </div>
        <div class="tab" data-target="#categories">
          <div class ="col-xs-1"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
          <div class ="col-xs-7 col-xs-offset-1 dashboard-text"><h4>Categories</h4></div>
          <div class ="col-xs-3 text-right"><i class="fa fa-angle-double-right" aria-hidden="true"></i></div>
        </div>
        <div class="tab" data-target="#newprescription">
          <div class ="col-xs-1"><i class="fa fa-plus-square" aria-hidden="true"></i></div>
          <div class ="col-xs-7 col-xs-offset-1 dashboard-text"><h4>Add a prescription</h4></div>
          <div class ="col-xs-3 text-right"><i class="fa fa-angle-double-right" aria-hidden="true"></i></div>
        </div>
        <div>
          <button type="button" class="btn checkout-button btn-block" onclick="createOrderProducts('<%= @order.id %>')" id="create-order-'<%= @order.id %>'">
            Checkout
          </button>
        </div>
      </div>
    </div>
    <div class="context-container col-xs-8">
      <div class="tab-content active" id="suggestedcats">
        <%= render 'suggested_categories_show', orders: @orders, product: @product %>
      </div>
      <div class="tab-content hidden" id="allmedicines">
        <%= render 'all_medicines', order: @order, product: @product  %>
      </div>
      <div class="tab-content hidden" id="categories">
        <%= render 'suggested_categories_show', order: @order, product: @product  %>
      </div>
      <div class="tab-content hidden" id="newprescription">
        <%= render 'new_prescription' %>
      </div>
    </div>

  </div>
</div>


<% content_for(:after_js) do %>
<script>

  $(document).ready(function () {
    $(function(){

      $(".tab").on("click", function(e){
        // Change active tab
        $('.tab').removeClass('active')
        $(this).addClass('active')

        // Hide all tab-content (use class="hidden")
        $('.tab-content').addClass('hidden')

        // Show target tab-content (use class="hidden")
        var id = $(".active").data("target")
        $(id).removeClass('hidden')
      });
    });
  });
  $('.addproduct').hide();
  function showAddDiv(id) {
    $('#add-' + id).show();
  }
  function hideDiv(id) {
    $('#add-' + id).hide();
  }
</script>
<% end %>

app/views/orders/show.html.erb
<div class="dashboard-wrapper">
  <div class="row">
    <h1 class="text-center">Order overview</h1>
    <hr/>
    <div class="col-xs-offset-1 col-xs-6">
      <div class="checkout-product-container">
        <h3> Products in cart:</h3>
        <hr/>

        <% @order.order_products.each do |order_product| %>
        <ul>
          <p> <%= order_product.quantity %> | <%= order_product.product.name %> </p>
          <% total_price = order_product.quantity * order_product.product.price  %>
          <p> Price: <%= total_price %>€, per item: <%= order_product.product.price %>€ </p>

          <!-- show small pic? -->
          </ul>

        <% end %>
        <hr/>
        <h4> Sub total: <%= @order.amount %>€ </h4>
    </div>
  </div>

  <div class="col-xs-4">
    <div class="checkout-content-container-address">
      <% if current_user.customer.customer_addresses.empty? %>
      <h4> Please enter delivery address:</h4>
      <div id="order-address-form">
        <h4> <strong> <%= current_user.first_name + " " + current_user.last_name %> </strong> </h4>
        <%= simple_form_for @customer_address, url: customer_customer_addresses_path(@customer), remote: true do |f| %>
        <%= f.input :address, placeholder: 'E.g Orla Lehmanns allé 8, 1. 8000 Aarhus C' %>
        <%= f.submit "add address", class: "btn btn-primary", id: "address-submit" %>
        <% end %>
      </div>
      <% else %>
      <div>
        <h3 id="checkout-address">Delivery address:</h3>
        <h4> <strong> <%= current_user.first_name + " " + current_user.last_name %> </strong>  </h4>
        <h4> <span id="front-customer-address"> <%= current_user.customer.customer_addresses.last.address %> </span> </h4>
        <button type="button" class="btn update-address-button btn-sm" data-toggle="modal" data-target="#EditAddressModal">
          Change delivery address
        </button>
      </div>
      <% end %>
      <br>
      <button type="button" class="btn checkout-button btn-block" data-toggle="modal" data-target="#ConfirmModal" id="confirm-modal-button">
        Review order and checkout
      </button>
    </div>
  </div>
</div>
</div>
</div>

<!-- Update address modal -->
<div class="modal fade(1000) text-center" id="EditAddressModal" tabindex="-1" role="dialog" aria-labelledby="testLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Enter new delivery address</h4>
      </div>
      <div class="modal-body">
        <div class="text-center">
          <%= simple_form_for @customer_address, url: customer_customer_addresses_path(@customer), remote: true do |f| %>
          <%= f.input :address, placeholder: 'E.g Orla Lehmanns allé 8, 1. 8000 Aarhus C' %>
          <%= f.submit "Update address", class: "btn btn-success btn-block", id: "address-submit" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- final checkout modal -->
<div class="modal fade(1000) text-center" id="ConfirmModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Review your order</h4>
      </div>
      <div class="modal-body">
        <div class="text-center">
          <h4> <strong> <%= current_user.first_name + " " + current_user.last_name %> </strong> </h4>
          <h4> <%= current_user.email %> </h4>
          <h4> <span id="confirm-modal-address"> </span> </h4>
          <h4>Products:</h4>
          <% @order.order_products.each do |order_product| %>
          <ul><%= order_product.quantity %> | <%= order_product.product.name %></ul>
          <% end %>
        </div>
        <h4> Finalize order and pay below </h4>
        <hr/>
        <%= form_tag order_payments_path(@order) do %>
        <article>
          <label class="amount">
            <span>Total amount: <%= humanized_money_with_symbol(@order.amount) %></span>
            </label>
          </article>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-name="My Order"
            data-email="<%= current_user.email %>"
            data-description="Order <%= @order.id %>"
            data-amount="<%= @order.amount_cents %>"
            data-currency="<%= @order.amount.currency %>"></script>
        <% end %>
        <br>
        <!-- <div class="modal-footer"> -->
          <!-- <button type="button" class="btn btn-default" data-dismiss="modal"></button> -->
          <!-- <button type="button" class="btn checkout-button btn-block">Place order</button> -->
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
<script>
  console.log("yolo")
  <% if current_user.customer.customer_addresses.empty? %>
  $("#confirm-modal-button").addClass("hidden")
  <% else %>
    $("#confirm-modal-button").click(function () {
      console.log("main jquery")
      var newAddress = $("#front-customer-address").text()
      $("#confirm-modal-address").html(newAddress);
    });
  <% end %>


</script>
<% end %>