config/routes.rb
Rails.application.routes.draw do

  get 'prescriptions/new'

  authenticated :user do
    root :to => 'passthrough#minirouter' # Look up the PassthroughController
  end

  devise_scope :user do
    root to: "users/registrations#new"
  end

  get 'drivers/new',                to: 'driver_registrations#new'
  get 'drivers/switch',             to: 'drivers#switch'
  post 'drivers',                   to: 'driver_registrations#create'
  post 'drivers/verify',            to: 'drivers#verify'

  get 'prescriptions/new',          to: 'prescriptions#new'
  post 'prescriptions/create',       to: 'prescriptions#create'


  get 'orders/claim',               to: 'orders#claim'
  post 'order/add_to_cart',         to: 'orders#add_to_cart'



  devise_for :users, controllers: { registrations: "users/registrations" }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # resources :order_products, only: [ :index, :show, :new, :create ] do
    #   resources :products, only: :create
    # end

  resources :customers, only: [ :show]
  resources :drivers, only: [ :show ]
  resources :verification_codes
    resources :products, only: [ :index, :show, :new, :create ] do
      resources :order_products, only: [ :index, :show, :new, :create ]
    end
    resources :orders, only: [ :index, :show, :new, :create ] do
      resources :payments, only: [ :create]
      resources :order_products, only: [ :index, :show, :new, :create ] do
        resources :products, only: [ :index, :show, :new, :create ]
      end
    end
    resources :customers, only: [ :show] do
      resources :customer_addresses, only: [ :create]
    end

    resources :drivers, only: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :customer_addresses
  has_many :orders
  def full_name
    "#{user.firt_name} #{user.last_name}"
  end
end

app/models/customer_address.rb
class CustomerAddress < ApplicationRecord
  belongs_to :customer
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :user
  has_many :orders

  include AASM

  aasm :column => :status do
    state :inactive, :initial => true
    state :active

    event :activate do
      transitions :from => :inactive, :to => :active
    end

    event :deactivate do
      transitions :from => :active, :to => :inactive
    end

  end

  aasm :column => :verification_status do
    state :unverified, :initial => true
    state :verified

    event :verify do
      transitions :from => :unverified, :to => :verified
    end

  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :driver, optional: true
  has_many :order_products, inverse_of: :order
  has_many :products, through: :order_products

  monetize :amount_cents

  accepts_nested_attributes_for :order_products

  include AASM

  aasm do
    state :unpaid, initial: true
    state :unclaimed
    state :claimed
    state :shopping
    state :processed
    state :delivered

    event :unpaid do
      transitions from: [ :claimed, :shopping, :processed, :delivered, :unclaimed ], to: :unpaid
    end

    event :unclaim do
      transitions from: :unpaid, to: :unclaimed
    end

    event :claim do
      transitions from: :unclaimed, to: :claimed
    end

    event :shop do
      transitions from: :claimed, to: :shopping
    end

    event :process do
      transitions from: :shopping, to: :processed
    end

    event :deliver do
      transitions from: :processed, to: :delivered
    end

  end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order, inverse_of: :order_products
  belongs_to :product

  accepts_nested_attributes_for :product
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :customer

  validates :interval, inclusion: { in: [ "weekly", "monthly", "bimonthly", "yearly" ] }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products
  has_many :orders, through: :order_products
  has_attachment :photo
  monetize :price_cents

  def to_s
    name
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    @product.photo_url = product_params[:photo_url]
    @product.save!
  end

  private

  def product_params
    params.require(:product).permit(:name, :photo)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :customer
  has_one :driver
end

app/models/verification_code.rb
class VerificationCode < ApplicationRecord
  belongs_to :user
end

app/controllers/driver_registrations_controller.rb
class DriverRegistrationsController < Devise::RegistrationsController
  skip_before_action :authenticate_user!, only: [:new]
  layout 'driver_registrations'

  def new
    @user = User.new
    render 'driver_registrations/new'
  end

  def create
    super
    user.driver.create
  end

  def devise_mapping
    Devise.mappings[:user]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    authorize @pages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/passthrough_helper.rb
module PassthroughHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/driver_registrations/new.html.erb
<div class="banner" style="background: linear-gradient(-225deg, rgba(0,0,0,0.2) 0%, rgba(0,0,0,0.2) 50%), url( <%= image_path('delivery.jpg') %> );">

  <div class="login test">
    <%= image_tag 'pharmago.png', id: 'logo'  %>
    <br>
    <h4>Have your own schedule and earn <strong> money </strong>by helping people</h4>
    <br>
    <div style="padding-left: 50px; padding-right: 50px;">
      <%= simple_form_for(User.new, as: :user, url: registration_path(:user)) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <div class="row" ;">
          <div class="col-xs-6">
            <%= f.input :first_name, required: true, :class => "First Name", autofocus: true, placeholder: "First Name", label: false %>
          </div>
          <div class="col-xs-6">
            <%= f.input :last_name, required: true, :class => "Last Name", autofocus: true, placeholder: "Last Name", label: false %>
          </div>
        </div>
        <%= f.input :email, required: true, placeholder: "Your Email", label: false, autofocus: true %>
        <div class="form-group">
          <%= f.text_field :country_code, class: "form-control", placeholder: "Your Country Code", label: false, id: "authy-countries" %>
        </div>
        <div class="form-group">
          <%= f.text_field :phone_number, class: "form-control", placeholder: "Your Phone Number", label: false, id: "authy-cellphone" %>
        </div>
        <%= f.input :password, required: true, placeholder: "Password", label: false, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
        <%= f.input :password_confirmation, placeholder: "Password Confirmation", label: false, required: true %>

      </div>

       <div class="form-actions" style="padding-bottom: 10px;">
        <%= f.button :submit, "Sign up as a Driver", :class => 'btn btn-primary sign-up' %>
      </div>
      <% end %>
    </div>
    <div>
      <h5>Already a User? Click <%= render "devise/shared/links" %></h5>
    </div>
  </div>
</div>

app/views/driver_registrations/show_verify.html.erb
<h1>Just To Be Safe...</h1>
<p>
    Your account has been created, but we need to make sure you're a human
    in control of the phone number you gave us. Can you please enter the
    verification code we just sent to your phone?
</p>
<%= form_tag users_verify_path do %>
  <div class="form-group">
    <%= label_tag :code, "Verification Code:" %>
    <%= text_field_tag :token, '', class: "form-control" %>
  </div>
  <button type="submit" class="btn btn-primary">Verify Token</button>
<% end -%>

<hr>
<%= form_tag users_resend_path do %>
  <button type="submit" class="btn">Resend code</button>
<% end -%>