config/routes.rb
Rails.application.routes.draw do

  get 'prescriptions/new'

  authenticated :user do
    root :to => 'passthrough#minirouter' # Look up the PassthroughController
  end

  devise_scope :user do
    root to: "users/registrations#new"
  end

  get 'drivers/new',                to: 'driver_registrations#new'
  get 'drivers/switch',             to: 'drivers#switch'
  post 'drivers',                   to: 'driver_registrations#create'
  post 'drivers/verify',            to: 'drivers#verify'

  get 'prescriptions/new',          to: 'prescriptions#new'
  post 'prescriptions/create',       to: 'prescriptions#create'


  get 'orders/claim',               to: 'orders#claim'
  post 'order/add_to_cart',         to: 'orders#add_to_cart'



  devise_for :users, controllers: { registrations: "users/registrations" }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # resources :order_products, only: [ :index, :show, :new, :create ] do
    #   resources :products, only: :create
    # end

  resources :customers, only: [ :show]
  resources :drivers, only: [ :show ]
  resources :verification_codes
    resources :products, only: [ :index, :show, :new, :create ] do
      resources :order_products, only: [ :index, :show, :new, :create ]
    end
    resources :orders, only: [ :index, :show, :new, :create ] do
      resources :payments, only: [ :create]
      resources :order_products, only: [ :index, :show, :new, :create ] do
        resources :products, only: [ :index, :show, :new, :create ]
      end
    end
    resources :customers, only: [ :show] do
      resources :customer_addresses, only: [ :create]
    end

    resources :drivers, only: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :customer_addresses
  has_many :orders
  def full_name
    "#{user.firt_name} #{user.last_name}"
  end
end

app/models/customer_address.rb
class CustomerAddress < ApplicationRecord
  belongs_to :customer
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :user
  has_many :orders

  include AASM

  aasm :column => :status do
    state :inactive, :initial => true
    state :active

    event :activate do
      transitions :from => :inactive, :to => :active
    end

    event :deactivate do
      transitions :from => :active, :to => :inactive
    end

  end

  aasm :column => :verification_status do
    state :unverified, :initial => true
    state :verified

    event :verify do
      transitions :from => :unverified, :to => :verified
    end

  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :driver, optional: true
  has_many :order_products, inverse_of: :order
  has_many :products, through: :order_products

  monetize :amount_cents

  accepts_nested_attributes_for :order_products

  include AASM

  aasm do
    state :unpaid, initial: true
    state :unclaimed
    state :claimed
    state :shopping
    state :processed
    state :delivered

    event :unpaid do
      transitions from: [ :claimed, :shopping, :processed, :delivered, :unclaimed ], to: :unpaid
    end

    event :unclaim do
      transitions from: :unpaid, to: :unclaimed
    end

    event :claim do
      transitions from: :unclaimed, to: :claimed
    end

    event :shop do
      transitions from: :claimed, to: :shopping
    end

    event :process do
      transitions from: :shopping, to: :processed
    end

    event :deliver do
      transitions from: :processed, to: :delivered
    end

  end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order, inverse_of: :order_products
  belongs_to :product

  accepts_nested_attributes_for :product
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :customer

  validates :interval, inclusion: { in: [ "weekly", "monthly", "bimonthly", "yearly" ] }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products
  has_many :orders, through: :order_products
  has_attachment :photo
  monetize :price_cents

  def to_s
    name
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    @product.photo_url = product_params[:photo_url]
    @product.save!
  end

  private

  def product_params
    params.require(:product).permit(:name, :photo)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :customer
  has_one :driver
end

app/models/verification_code.rb
class VerificationCode < ApplicationRecord
  belongs_to :user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    authorize @pages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/passthrough_helper.rb
module PassthroughHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title><%= Pharmago %></title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Quicksand">
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= render 'shared/footer' %>

  <!-- <script type="text/javascript" src="slick/slick.min.js"></script> -->
  <%= javascript_include_tag 'application' %>
  <%= cloudinary_js_config %> <!-- Append this after the main `javascript_include_tag`. -->
  <%= yield(:after_js) %>
</body>
</html>

app/views/layouts/driver_registrations.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title><%= Pharmago %></title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>



</head>
<body>
  <% navbar_classes = %w(registrations passwords sessions driver_registrations).include?(controller_name) ? "navbar-wagon navbar-transparent" : "navbar-wagon navbar-opaque"  %>

  <div class="<%= navbar_classes %>">

    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <div>
        <%= link_to t(".top_call_to_action", default: "Be a Customer"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
      </div>
    </div>

  </div>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= yield(:after_js) %>
</body>
</html>

app/views/layouts/signup_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title><%= Pharmago %></title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>

</head>
<body>
  <% navbar_classes = %w(registrations passwords sessions driver_registrations).include?(controller_name) ? "navbar-wagon navbar-transparent" : "navbar-wagon navbar-opaque"  %>

  <div class="<%= navbar_classes %>">

    <div class="navbar-wagon-right hidden-xs hidden-sm">
     <div>
      <%= link_to t(".top_call_to_action", default: "Become a Driver"), drivers_new_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    </div>
    <div>
      <button type="button" class="navbar-wagon-item navbar-wagon-button btn" data-toggle="modal" data-target=".bs-example-modal-lg">How Pharmago works?</button>

      <%= render 'shared/modal_text' %>
    </div>
  </div>
</div>
<%= render 'shared/flashes' %>
<%= yield %>
<%= javascript_include_tag 'application' %>
<%= yield(:after_js) %>
</body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="wrapper-footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <ul class="list-inline">
          <li><a href=""><i class="fa fa-twitter fa-2x" style="color:white;"></i></a></li>
          <li><a href=""><i class="fa fa-facebook fa-2x" style="color:white;"></i></a></li>
          <li><a href=""><i class="fa fa-instagram fa-2x" style="color:white;"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-1">
        <p> About </p>
      </div>
      <div class="col-xs-1">
        <p> Press</p>
      </div>
      <div class="col-xs-1">
        <p> Privacy </p>
      </div>
      <div class="col-xs-1">
        <p> Help </p>
      </div>
      <div class="col-xs-4">
        <p class="footer-text">Developed by Team Elliot</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_text.html.erb
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="openmodel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content modal-custom main-text">
      <h1 style="text-align: center; font-size: 70px;">Welcome to <%= image_tag 'pharmago', id: 'logo'  %></h1>
      <h3 style="text-align: center">The world's quickest way for pharmaceutical delivery</h3> <br>
      <h4><strong>Using Pharmago as a customer</strong></h4>
      <h4>Buying medicine has never been so easy. With Pharmago you can easily buy medicine online and have it delivered to you the same day. This is why you never again have to worry about not having enough medicine at home in case you get sick. </h4>
      <h4>But it get's even better. With Pharmago you can store several adresses and have medicine delivered not only to yourself but also to your parents for example. You also have the feature that you can order your medicine regularily, so daily, weekly or on your own schedule. Still hesitating to signup? Just create an account and check Pharmago out. It's free to sign up so what are you waiting for? </h4> <br>

      <h4><strong>Using Pharmago as a driver</strong></h4>
      <h4>You have a car or bike? Then you are our perfect Partner! Getting paid for singing in your car with a schedule you can decide for yourself? Sounds like a dream! </h4>
      <h4>So what are you waiting for. Join our team and contribute to society by helping people to get their medicine! Just hit the top left button and become a driver!</h4> <br>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% navbar_classes = %w(registrations passwords sessions driver_registrations).include?(controller_name) ? "navbar-wagon navbar-transparent" : "navbar-wagon navbar-opaque"  %>

<div class="<%= navbar_classes %>">
  <!-- Logo -->

  <a href="/orders/new" class="navbar-wagon-brand">
    <%= image_tag "favicon.ico" %>
  </a>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <!-- Notification -->
      <% if current_user.customer %>
        <%= link_to "/", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
          <div class="badge badge-blue">
            <%= current_user.customer.orders.count %>

          </div>
        </div>
        <% end %>
      <% end %>

      <% if current_user.driver %>
        <%= link_to "/", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-ambulance" aria-hidden="true"></i>
          <div class="badge badge-blue">
            <% if current_user.customer %>
            <%= current_user.customer.orders.count %>
            <% elsif current_user.driver %>
            <%= current_user.driver.orders.count %>
            <% end %>
          </div>
        </div>
        <% end %>

        <div class="switch">
          <input type="checkbox" value="None" id="switch" name="check" checked />
          <label for="switch"></label>
        </div>
      <% end %>


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown" style="color: grey;">
          Account<%= image_tag "test.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <% if current_user.customer.present? %>
              <%= link_to customer_path(current_user) do %>
              <h4 style="color: grey; margin-bottom: 0px !important;">Hi, <%= current_user.first_name.capitalize %></h4>
              <% end %>
              <% else %>
              <%= link_to driver_path(current_user) do %>
              <h4 style="color: grey; margin-bottom: 0px !important;">Hi, <%= current_user.first_name.capitalize %></h4>
              <% end %>
              <% end  %>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <% if current_user.customer.present? %>
              <%= link_to customer_path(current_user) do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
              <% else %>
              <%= link_to driver_path(current_user) do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
              <% end  %>
            </li>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-shopping-cart"></i>  <%= t(".profile", default: "Orders") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <% else %>

    <!-- Login text link -->

    <% end %>

    <!-- Button (call-to-action) -->
  </div>
 <!--  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo1.png" %>
    <% end %> -->
    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Some mobile link</a></li>
          <li><a href="#">Other one</a></li>
          <li><a href="#">Other one</a></li>
        </ul>
      </div>
    </div>
  </div>

app/views/shared/_new_order.html.erb
<h1 style="padding-bottom: 20px;"> What medicine would you like to order? </h1>

<%= form_for(order) do |form| %>
  <%= form.fields_for :order_products, @order.order_products do |fform| %>
    <%= fform.select :product_id, @products.map {|p| [p.name, p.id]}  %>
      How many? : <%= fform.text_field :quantity %> <br>
    <% end %>
  <%= form.button :submit %>
<% end %>

app/views/shared/_new_prescription.html.erb
<div class="text-center">
  <%= simple_form_for Prescription.new, url: prescriptions_new_path, remote: true do |f| %>
    <%= f.input :number, placeholder: 'Prescription # here' %>
    <%= f.input :interval, placeholder: 'Weekly, monthly, bimonthly etc.' %>
    <%= f.submit "Add prescription", class: "btn btn-success btn-block" %>
  <% end %>
</div>

app/views/shared/_order_card.html.erb
<div id="confirm-<%= order.id %>" class="confirmation-content">
    Are you sure?

    <span onclick="claimOrder('<%= order.id %>');" class="btn btn-success order-claim" style="color: white;">
      YES
    </span>

    <span id="<%= order.id %>" onclick="hideThis('<%= order.id %>');" class="btn btn-danger order-claim" style="color: white;">
      NO
    </span>

</div>

<div id="card-<%= order.id %>" class="order-card">
  <div class="order-info">
    <h4> Deliver before: <br> <%= Time.now.asctime %> </h4>
  </div>
  <div>
    <h4> <strong> <%= order.customer.customer_addresses.last.address %> </strong> </h4>
  </div>
  <div class="order-interaction">
    <span onclick="showConfirmation('<%= order.id %>');" class="btn btn-success">Claim order</span>
  </div>
</div>


<% content_for(:after_js) do %>
  <script>

    // define functions below
    function claimOrder(id) {
      $.ajax({
        type:'GET',
        url:'/orders/claim',
        data: { id: id },
        success:function(){
          console.log("Done");
        }
      });
      $('#' + 'confirm-' + id).hide();
      $('#' + 'container-' + id).slideUp();
    }

    $('.confirmation-content').hide();

    function showConfirmation(id) {
      $('#' + 'confirm-' + id).fadeIn();
      $('#' + 'card-' + id).addClass('fadewhite');
    }

    function hideThis(id) {
      $("#" + id).parent('div').hide();
      $('#' + 'card-' + id).removeClass('fadewhite');
    }

    function showThis(id) {
      $("#" + id).parent('div').fadeIn();
    }

  </script>
<% end %>

app/views/shared/_product_card.html.erb
<div style=":focus {outline:0;}" onmouseenter="showQuantityControl('<%= product.id %>')" onmouseleave="hideQuantityControl('<%= product.id %>')" class="row">
  <div class="col-xs-12">
    <div class="card product-info" style="width: 150px; height: 150px; background-image: cover !important; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= product.url %>');">

      <div class="card-category" id='<%= product.id %>'> </div>
      <div data-product-id="<%= product.id %>" data-quantity=0 class="quantity-control" id='quantity-<%= product.id %>'>
        <span onclick="subtractOne('<%= product.id %>')" class="square subtract add-button" style="font-size: 10px;"><i class="fa fa-minus"></i></span>
        <span onclick="addOne('<%= product.id %>')" class="square add add-button" style="font-size: 10px;"><i class="fa fa-plus"></i> ADD</span>
      </div>
    </div>
    <div class="product-card">
      <h5><%= product.name %></h5>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>

    var orderProducts = {}

    function escapeHtml(text) {
      var map = {
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#039;'
      };

      return text.replace(/[&<>"']/g, function(m) { return map[m]; });
    }

    function createOrderProducts(id) {
      var jsonOrderProducts = JSON.stringify(orderProducts);

      var form = $('<form enctype="application/json" action="/order/add_to_cart/" method="POST">' +
        '<input type="hidden" name="json" value="' + escapeHtml(jsonOrderProducts) + '">' +
        '<input type="hidden" name="id" value="' + id + '">' +
        '</form>');

      $(document.body).append(form);
      form.submit();

      console.log(form.submit());
    }


    function addOne(id) {
      var newQuantity = $('#quantity-' + id).data('quantity') + 1
      $('#quantity-' + id).data('quantity', newQuantity);
      orderProducts[id] = newQuantity;
      console.log( orderProducts );
    };

    function subtractOne(id) {
      var quantity = $('#quantity-' + id).data('quantity')
      if ( quantity > 1 ) {
        var newQuantity = quantity - 1
        $('#quantity-' + id).data('quantity', newQuantity)
        orderProducts[id] = newQuantity;
        console.log( orderProducts );
      }
      else {
        $('#quantity-' + id).data('quantity', 0)
        orderProducts[id] = newQuantity;
        delete orderProducts[id];
        console.log( orderProducts );
      }
      var subtractQuantity = $('#quantity-' + id).data('quantity') - 1
      $('#quantity-' + id).data('quantity', newQuantity)
      console.log(  $('#quantity-' + id).data('quantity')  );

    };

    // define functions below
    function addItem(id) {
      $.ajax({
        type:'GET',
        url:'/orders/claim',
        data: { id: id },
        success:function(){
          console.log("Done");
        }
      });
      $('#' + 'confirm-' + id).hide();
      $('#' + 'container-' + id).slideUp();
    }

    $('.quantity-control').hide();

    function showQuantityControl(id) {
      $('#' + 'quantity-' + id).show();
    }

    function hideQuantityControl(id) {
      $('#' + 'quantity-' + id).hide();
    }

    function hideThis(id) {
      $("#" + id).parent('div').hide();
      $('#' + 'card-' + id).removeClass('fade');
    }

    function showThis(id) {
      $("#" + id).parent('div').fadeIn();
    }

  </script>
<% end %>

app/views/shared/_verification_code.erb
  <%= simple_form_for :driver, url: drivers_verify_path, :method => :post do |f| %>
    <%= f.input :verification_code, label: false, input_html: { value: nil, placeholder: "Your 5 digit verification code" } %>
    <%= f.button :submit %>
  <% end %>